/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.
 *
 * Interoperability test: reads a TsFile generated by Rust code.
 * Usage: java -cp ... org.apache.tsfile.InteropTestRead <path-to-rust-tsfile>
 */

package org.apache.tsfile;

import org.apache.tsfile.read.TsFileReader;
import org.apache.tsfile.read.common.Path;
import org.apache.tsfile.read.expression.QueryExpression;
import org.apache.tsfile.read.query.dataset.QueryDataSet;

import java.io.File;
import java.io.IOException;

/** Reads a TsFile generated by Rust and verifies the data. */
public class InteropTestRead {

  public static void main(String[] args) throws Exception {
    if (args.length < 1) {
      System.err.println("Usage: java InteropTestRead <path-to-tsfile>");
      System.exit(1);
    }

    String path = args[0];
    File f = new File(path);
    if (!f.exists()) {
      System.err.println("File not found: " + path);
      System.exit(1);
    }

    System.out.println("Reading TsFile: " + path);
    readTsFile(f);
  }

  /** Read and print all data from the TsFile. */
  public static void readTsFile(File file) throws IOException {
    try (TsFileReader reader = new TsFileReader(file)) {
      // Read device1/sensor1
      try {
        QueryExpression queryExpression =
            QueryExpression.create().addSelectedPath(new Path("device1", "sensor1", true));

        QueryDataSet dataSet = reader.query(queryExpression);

        int count = 0;
        while (dataSet.hasNext()) {
          System.out.println(dataSet.next());
          count++;
        }
        System.out.println("Total records read: " + count);
      } catch (Exception e) {
        System.err.println("Error reading device1/sensor1: " + e.getMessage());
        e.printStackTrace();
      }
    }
    System.out.println("Done reading: " + file.getName());
  }
}
